core/api/urls.py
from django.urls import path
from .views import ImageAPIView

urlpatterns = [
    path('id/<id>', ImageAPIView.as_view()),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('images/', include('images.urls', namespace='images')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/images/urls.py
from re import template
from django.urls import path
from django.views.generic import TemplateView
from .views import ImageListView

app_name = 'images'

urlpatterns = [
    path('', TemplateView.as_view(template_name='images/index.html')),
    path('all/', ImageListView.as_view(), name='all_images'),
]

core/api/models.py
from django.db import models

# Create your models here.

core/images/models.py
from django.db import models
from django.contrib.auth.models import User

def user_directory_path(instance, filename):
    return f'images/{filename}'


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

class Image(models.Model):
    options = (
        ('active','Active'),
        ('deactivated','Deactivated'),
    )

    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=255)
    alt = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, default='post/default.jpg')
    slug = models.SlugField(max_length=255, unique_for_date='created')
    created = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='author')
    status = models.CharField(max_length=12, choices=options, default='active')
    

core/api/views.py
from tkinter import Image
from xmlrpc.client import ResponseError
from rest_framework import generics
from .renderers import JPEGRenderer, PNGRenderer
from images.models import Image
from rest_framework.response import Response

class ImageAPIView(generics.RetrieveAPIView):

    renderer_classes = [JPEGRenderer]
    
    def get(self, request, *args, **kwargs):
        queryset = Image.objects.get(id=self.kwargs['id']).image
        data = queryset
        return Response(data, content_type='image/jpg')

core/images/views.py
from django.views.generic import ListView
from .models import Category, Image

class ImageListView(ListView):
    model = Image
    template_name = 'images/all_images.html'

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <title>{% block title %}Image API{% endblock%}</title>

    <style>
      .small {
        font-size: 0.875rem;
        color: #4b4b4b;
      }
    </style>
  </head>

  <body>
    {% block content%} {% endblock %}
  </body>

  <script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>
</html>

core/templates/footer.html
<footer class="font-small bg-dark pt-4">
  <div class="container">
    <ul class="py-2"></ul>
  </div>
  <div class="py-3"></div>
</footer>

core/templates/images/all_images.html
{% extends "base.html" %}
{% block title %}
Welcome to Blog
{% endblock %}
{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&family=Roboto:wght@500&display=swap');

    h1 {
        font-family: 'Work Sans', sans-serif;
        font-weight: 600;
    }

    .txt-robo {
        font-family: 'Roboto', sans-serif;
        font-weight: 500
    }

    p {
        font-family: 'Open Sans', sans-serif;
    }

    h4 {
        font-weight: 300
    }

    .bg-dark {
        background-color: #000000 !important;
    }

    .fs14 {
        font-size: 14px;
    }
</style>
<div class="container" style="max-width: 1240px;">
    <div class="row pt-5">
        <div class="col-12 col-md-6">
            <section class="jumbotron bg-white">
                <div class="container">
                    <h1 class="pt-4"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                            <path
                                d="M10.648 7.646a.5.5 0 0 1 .577-.093L15.002 9.5V13h-14v-1l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71z" />
                            <path fill-rule="evenodd" d="M4.502 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
                        </svg> VeryPicSum
                    </h1>
                    <p class="h4">Image API Placeholders.</p>
                </div>
            </section>
        </div>
        <div class=" d-none d-md-none d-md-block col-md-6">
            <section class="jumbotron text-center bg-white px-0">
                <div class="container">
                    <img class="shadow mb-5 bg-white rounded" src="#" width="100%">
                </div>
            </section>
        </div>
    </div>
</div>
<section class="jumbotron text-center">
    <div class="container" style="max-width: 600px;">
        <h1 class="txt-robo h1">Easy to use placeholders</h1>
        <p>Just find an image and create a URL, not quite implemented width and height yet!</p>

        <pre class="bg-white pt-3"><code><a href="#">https://127.0.0.1:8000/api/id/2</a></code>
        </pre>

    </div>
</section>

<div class="container">
    <div class="py-5">
        <div class="row">
            {% for post in object_list %}
            <div class="col-md-4">
                <a class="text-dark" href="{{post.get_absolute_url}}">
                    <div class="card mb-4 shadow mb-5 bg-white rounded">
                        <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                        <div class="card-body d-flex justify-content-between ">
                            <p>{{post.title|truncatechars:50}}</p>
                            <p>#{{post.id}}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "footer.html" %}
{% endblock %}

core/templates/images/index.html
{% extends "base.html" %}
{% block title %}
Welcome to Blog
{% endblock %}
{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&family=Roboto:wght@500&display=swap');

    h1 {
        font-family: 'Work Sans', sans-serif;
        font-weight: 600;
    }

    .txt-robo {
        font-family: 'Roboto', sans-serif;
        font-weight: 500
    }

    p {
        font-family: 'Open Sans', sans-serif;
    }

    h4 {
        font-weight: 300
    }

    .bg-dark {
        background-color: #000000 !important;
    }

    .fs14 {
        font-size: 14px;
    }
</style>
<div class="container" style="max-width: 1240px;">
    <div class="row pt-5">
        <div class="col-12 col-md-6">
            <section class="jumbotron bg-white">
                <div class="container">
                    <h1 class="pt-4"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                            <path
                                d="M10.648 7.646a.5.5 0 0 1 .577-.093L15.002 9.5V13h-14v-1l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71z" />
                            <path fill-rule="evenodd" d="M4.502 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
                        </svg> VeryPicSum
                    </h1>
                    <p class="h4">Image API Placeholders.</p>
                    <p class="text-muted">
                        Find a list of the images <a href="{% url 'images:all_images' %}">here</a>
                    </p>
                </div>
            </section>
        </div>
        <div class=" d-none d-md-none d-md-block col-md-6">
            <section class="jumbotron text-center bg-white px-0">
                <div class="container">
                    <img class="shadow mb-5 bg-white rounded" src="http://127.0.0.1:8000/api/id/1" width="100%">
                </div>
            </section>
        </div>
    </div>
</div>
<section class="jumbotron text-center">
    <div class="container" style="max-width: 600px;">
        <h1 class="txt-robo h1">Easy to use placeholders</h1>
        <p>Just find an image and create a URL, not quite implemented width and height yet!</p>

        <pre class="bg-white pt-3"><code><a href="#">https://127.0.0.1:8000/api/id/2</a></code>
        </pre>

    </div>
</section>
<div class="container" style="max-width: 1240px;">
    <div class="row pt-5">
        <div class="col-12 col-md-6">
            <section class="jumbotron bg-white">
                <div class="container">
                    <h1 class="pt-4 txt-robo h3"> Specific Image
                    </h1>
                    <p>Just find an image and create a URL, not quite implemented width and height yet!</p>
                    </p>
                    <pre class="bg-light text-center pt-3"><code><a href="http://127.0.0.1:8000/api/id/1">https://127.0.0.1:8000/api/id/1</a></code>
        </pre>
                </div>
            </section>
        </div>
        <div class="d-none d-md-none d-md-block col-md-6">
            <section class="jumbotron text-center bg-white px-0">
                <div class="container">
                    <img class="shadow mb-5 bg-white rounded" src="http://127.0.0.1:8000/api/id/1" width="100%">
                </div>
            </section>
        </div>
    </div>
</div>
{% include "footer.html" %}
{% endblock %}